"""Initial_Deployment

Revision ID: 127caddcc07f
Revises: 
Create Date: 2026-02-06 10:19:27.130276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127caddcc07f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_run_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id_article', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom_article', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('prix_vente', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantite_disponible', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('emplacement', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_article'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('idx_articles_nom_article_gin', 'articles', ['nom_article'], unique=False, postgresql_using='gin', postgresql_ops={'nom_article': 'gin_trgm_ops'})
    op.create_index('idx_articles_reference_gin', 'articles', ['reference'], unique=False, postgresql_using='gin', postgresql_ops={'reference': 'gin_trgm_ops'})
    op.create_table('clients',
    sa.Column('id_client', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom_client', sa.String(length=255), nullable=False),
    sa.Column('code_client', sa.String(length=100), nullable=False),
    sa.Column('matricule_fiscal', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('statut', sa.Enum('Resident', 'Non_Resident', name='clientstatus'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('code_client'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricule_fiscal')
    )
    op.create_table('historique_ventes_agregees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('chiffre_affaire', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('marge_brute', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annee', 'mois', name='_annee_mois_uc')
    )
    op.create_index(op.f('ix_historique_ventes_agregees_id'), 'historique_ventes_agregees', ['id'], unique=False)
    op.create_table('stock_se',
    sa.Column('id_se', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_se', sa.String(), nullable=False),
    sa.Column('date_importation', sa.Date(), nullable=False),
    sa.Column('quantite_totale', sa.Integer(), nullable=False),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('est_apure', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_se')
    )
    op.create_table('taux_de_change_mensuel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('taux', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('devise', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mois', 'annee', name='unique_mois_annee')
    )
    op.create_table('utilisateurs',
    sa.Column('id_utilisateur', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('gerant', 'employe', name='roleenum'), nullable=False),
    sa.Column('mot_de_passe', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_utilisateur'),
    sa.UniqueConstraint('mot_de_passe'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('apurements',
    sa.Column('id_apurement', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_se', sa.Integer(), nullable=False),
    sa.Column('date_echeance_initiale', sa.Date(), nullable=False),
    sa.Column('date_echeance_actuelle', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_se'], ['stock_se.id_se'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_apurement')
    )
    op.create_table('article_stock_association',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('stock_se_id', sa.Integer(), nullable=False),
    sa.Column('quantite_dans_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id_article'], ),
    sa.ForeignKeyConstraint(['stock_se_id'], ['stock_se.id_se'], ),
    sa.PrimaryKeyConstraint('article_id', 'stock_se_id')
    )
    op.create_table('bons_de_livraison',
    sa.Column('id_bl', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_bl', sa.Date(), nullable=False),
    sa.Column('numero_bl', sa.String(length=100), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('total_a_payer', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_bl'),
    sa.UniqueConstraint('numero_bl')
    )
    op.create_table('factures',
    sa.Column('id_facture', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_facture', sa.String(length=50), nullable=True),
    sa.Column('date_facture', sa.Date(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('montant_total_euro', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('montant_total_dt', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('remise_pourcentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('montant_net_euro', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('montant_net_dt', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('taux_conversion', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('poid_en_kg', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_en_lettre_euro', sa.Text(), nullable=True),
    sa.Column('total_en_lettre_dt', sa.Text(), nullable=True),
    sa.Column('numeros_se', sa.Text(), nullable=True),
    sa.Column('incoterm', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_facture'),
    sa.UniqueConstraint('numero_facture')
    )
    op.create_table('prediction_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('quantite_predite', sa.Integer(), nullable=False),
    sa.Column('date_prediction', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id_article'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'annee', 'mois', name='_article_annee_mois_uc')
    )
    op.create_index(op.f('ix_prediction_stock_id'), 'prediction_stock', ['id'], unique=False)
    op.create_table('prix_achat',
    sa.Column('id_prix_achat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prix_achat', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id_article'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_prix_achat')
    )
    op.create_table('facture_bon_livraison',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_facture', sa.Integer(), nullable=False),
    sa.Column('id_bl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_bl'], ['bons_de_livraison.id_bl'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_facture'], ['factures.id_facture'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ligne_bl',
    sa.Column('id_ligne_bl', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_bl', sa.Integer(), nullable=False),
    sa.Column('id_article', sa.Integer(), nullable=False),
    sa.Column('nom_article_archive', sa.String(length=255), nullable=True),
    sa.Column('categorie_archive', sa.String(length=100), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('prix_total_ligne', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('stock_se_id', sa.Integer(), nullable=False),
    sa.Column('remise', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_article'], ['articles.id_article'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_bl'], ['bons_de_livraison.id_bl'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_se_id'], ['stock_se.id_se'], ),
    sa.PrimaryKeyConstraint('id_ligne_bl')
    )
    op.create_table('historique_ventes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_article', sa.Integer(), nullable=True),
    sa.Column('date_vente', sa.Date(), nullable=True),
    sa.Column('quantite_vendue', sa.Integer(), nullable=True),
    sa.Column('montant_total', sa.Float(), nullable=True),
    sa.Column('id_facture', sa.Integer(), nullable=True),
    sa.Column('id_ligne_bl', sa.Integer(), nullable=True),
    sa.Column('prix_achat', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_article'], ['articles.id_article'], ),
    sa.ForeignKeyConstraint(['id_facture'], ['factures.id_facture'], ),
    sa.ForeignKeyConstraint(['id_ligne_bl'], ['ligne_bl.id_ligne_bl'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historique_ventes_id'), 'historique_ventes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historique_ventes_id'), table_name='historique_ventes')
    op.drop_table('historique_ventes')
    op.drop_table('ligne_bl')
    op.drop_table('facture_bon_livraison')
    op.drop_table('prix_achat')
    op.drop_index(op.f('ix_prediction_stock_id'), table_name='prediction_stock')
    op.drop_table('prediction_stock')
    op.drop_table('factures')
    op.drop_table('bons_de_livraison')
    op.drop_table('article_stock_association')
    op.drop_table('apurements')
    op.drop_table('utilisateurs')
    op.drop_table('taux_de_change_mensuel')
    op.drop_table('stock_se')
    op.drop_index(op.f('ix_historique_ventes_agregees_id'), table_name='historique_ventes_agregees')
    op.drop_table('historique_ventes_agregees')
    op.drop_table('clients')
    op.drop_index('idx_articles_reference_gin', table_name='articles', postgresql_using='gin', postgresql_ops={'reference': 'gin_trgm_ops'})
    op.drop_index('idx_articles_nom_article_gin', table_name='articles', postgresql_using='gin', postgresql_ops={'nom_article': 'gin_trgm_ops'})
    op.drop_table('articles')
    op.drop_table('aggregation_history')
    # ### end Alembic commands ###
